blog/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView,UserPostListView

urlpatterns=[
    path('',views.PostListView.as_view(),name="blog-home"),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name="post-detail"),
    path('post/new/',views.PostCreateView.as_view(),name="post-create"),
    path('post/<int:pk>/update/',views.PostUpdateView.as_view(),name="post-update"),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name="post-delete"),
    path('about/',views.about,name="blog-about"),
    path('ajax/postlike/<int:pk>/',views.PostLike,name="post-like"),
    path('ajax/postcomment/<int:pk>/',views.PostComment,name="post-comment"),
    path('ajax/commentupdate/<int:pk>/',views.CommentUpdate,name="comment-update"),
    path('ajax/commentdelete/<int:pk>/',views.CommentDelete,name="comment-delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
    path('password-reset/',
    auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
    name="password_reset"),
    path('password-reset/done/',
    auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
    name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
    name="password_reset_confirm"),
    path('password-reset-complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
    name="password_reset_complete"),
    path('profile/',user_views.profile,name="profile"),
    path('', include('blog.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=64)
    content=models.TextField()
    date_posted=models.DateTimeField(default=timezone.now)
    author=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk':self.pk})

        
    
    
class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ManyToManyField(User)
    counter=models.IntegerField(default=0)
    like_dated=models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f'post like {self.post.title},{self.counter}'

class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    user=models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True)
    content=models.TextField()
    timestam=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'post comment by  {self.user.username},{self.post.title}'   

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from .models import Post,Like,Comment
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

# Create your views here.
def home(request):
    context={
        'posts':Post.objects.all()
    }
    return render(request,'blog/home.html',context)
class PostListView(ListView):
    model=Post
    template_name='blog/home.html'
    # context_object_name='posts'
    ordering=['-date_posted']
    paginate_by = 5


class PostDetailView(DetailView):
    model=Post
    context_object_name='post'

class PostCreateView(LoginRequiredMixin,CreateView):
    model=Post
    fields=['title','content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=Post
    fields=['title','content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model=Post
    success_url='/'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class UserPostListView(ListView):
    model=Post
    template_name='blog/user_posts.html'
    context_object_name='posts'
    paginate_by = 5

    def get_queryset(self):
        user=get_object_or_404(User,username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')
    

        
def about(request):
    return render(request,'blog/about.html',{'title':'about'})

def PostLike(request,pk):
    like_post=Like.objects.filter(
        user__username=request.user,post_id=pk
    ).first()
    if like_post:
        like_post.delete()
        likes=Like.objects.filter(post_id=pk)
        total_likes=sum((like.counter) for like in likes)
        return JsonResponse({'total_likes':total_likes})
    
    else:
        post=Post.objects.get(pk=pk)
        like=Like(post=post,counter=1)
        like.save()
        user=User.objects.get(username=request.user)
        like.user.add(user)
        likes=Like.objects.filter(post_id=pk)
        total_likes=sum((like.counter) for like in likes)
        return JsonResponse({'total_likes':total_likes})
    
def PostComment(request,pk):
    data=dict()
    print('dfgh')
    post=get_object_or_404(Post,pk=pk)
    if request.method=='POST':
        content=request.POST.get('comment')
        print(content)
        user=User.objects.get(username=request.user)
        if post and content and user:
            comment=Comment(post=post,user=user,content=content)
            comment.save()
    post_comments=Comment.objects.filter(post=post).order_by('-timestam')
    data['comments']=render_to_string('blog/partial__comments.html',context={'post':post_comments},request=request)
    return JsonResponse(data)
    
def CommentUpdate(request,pk):
    comment=Comment.objects.get(pk=pk)
    try:
        data=dict()
        print("comment",comment)
        if request.method=='POST':
            content=request.POST.get('content')
            print(content)
            comment.content=content
            comment.save()
    except Exception as error:
        print(error)
    data['update_comment']=render_to_string('blog/update_comment.html',context={'content':comment},request=request)
    return JsonResponse(data)

def CommentDelete(request,pk):
    comment=Comment.objects.get(pk=pk)
    data=dict()
    tag=request.GET.get('tag')
    if tag == 'delete':
        comment.delete()
        return JsonResponse({'status':'comment delete succesully'})
    data['comment_delete']=render_to_string('blog/delete_comment.html',context={'content':comment},request=request)
    data['status']='ok'
    return JsonResponse(data)

blog/templates/blog/about.html
{% extends 'blog/base.html'%}
{% block content %}

<h1>About page</h1>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
            <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
    <title>Django Blog - {{ title }}</title>
    {% else %}
    <title>Django Blog</title>
    {% endif %}

    <script>

 
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');
  
 

    </script>
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
                    </div>
                    <!-- Navbar Right Side -->

                    <div class="navbar-nav">
                        {% if request.user.is_authenticated %}
                        <a  class="nav-item nav-link" href="{% url 'post-create'%}">Create Post</a>
                        <a  class="nav-item nav-link" href="{% url 'profile'%}">Profile</a>
                        <a  class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
                        

                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register'%}">Register</a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container " style="margin-top: 5rem;">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

  
</body>

</html>

blog/templates/blog/delete_comment.html
      
    
            <!-- Modal Header -->
            
            <div class="modal-header">
                <h4 class="modal-title">Are you sure you want to delete this comment?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            
            <!-- Modal body -->
            <div class="modal-body">
                <p>{{content.content}}</p>
            </div>
            
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger delete_comment" data-dismiss="modal" data-url="{% url 'comment-delete' content.pk %}">Delete</button>
            </div>

            <script>
                $(function(){
                    $('.delete_comment').click(function(){
                        $.ajax({
                            url:$(this).attr('data-url'),
                            type:'get',
                            data:{
                                'tag':'delete'
                            },
                            dataType:'json',
                            success:function(response){
                                if(response.status){
                                    console.log(response.status);
                                    RenderAllcomments() 

                                }

                            }
                        })
                    })
                })
            </script>

blog/templates/blog/home.html
{% extends 'blog/base.html'%}
{% block content %}
{% for post in post_list %}
<article class="media content-section">
  <img class="rounded-circle article-img" src={{post.author.profile.image.url}} alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' post.author.username%}">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted|date:"F d,Y"}}</small>
    </div>
    <h2><a class="article-title" href="{% url 'post-detail' post.pk%}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
  
</article>
{% endfor %}
{% if is_paginated %}

{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}

{% endif %}

<script>

</script>

{% endblock content %}

blog/templates/blog/partial__comments.html
{% for comment in post%}
  <div class="container comment__body" style="margin-top: 1rem;">
    <div class="col-md-2"></div>

    <div class="form-floating col-md-10 " id="commentBox" style="padding:1rem;display: flex;flex-direction: row;border-radius: 1rem;
    -moz-box-shadow: 0 0 3px #ccc;
    -webkit-box-shadow: 0 0 3px #ccc;
    box-shadow: 0 0 3px #ccc; 
    ">
    
      <img class="rounded-circle article-img" src={{comment.user.profile.image.url}} alt="" style="margin-right: 1rem;">
      <div style="display: flex;flex: 1;flex-direction: column;">
        <span >
            <a class="text-muted" style="font-size: 14px;font-weight: bold;text-decoration: none;" href="{% url 'user-posts' comment.user.username%}">{{comment.user.username}}</a>
             <span
            style="margin-left: .5rem;font-size: 14;font-weight: initial;">{{comment.timestam|date:"F d, Y"}}
        </span>
        <span class="dropdown"> 

            <i class="fa fa-ellipsis-h " style="float: right;cursor: pointer;" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {% if  comment.user == request.user%}
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item update" href="#" data-url="{% url 'comment-update' comment.pk %}">Edit</a>
                    <a class="dropdown-item delete" href="#" data-url="{% url 'comment-delete' comment.pk %}">Delete</a>
                </div>
                {% endif%}
            </i>

        </span>
        </span>
        

        <textarea class="form-control comments" disabled="disabled"
          style="border-radius: 10px;padding: 1rem;outline: none;background-color: white;cursor: initial;">{{comment.content}}</textarea>
      </div>    
    </div>
  </div>

  <script>
      $(function(){
        $('.update').click(function(){
            
            $.ajax({
                url:$(this).attr('data-url'),
                type:'get',
                dataType:'json',
                success:function(response){
                // $('#myModal').modal('show')
            
                    $("#modal-book .modal-content").html(response.update_comment);

                    $("#modal-book").modal("show");
                }
            })
        })
        $('.delete').click(function(){
        $.ajax({
            url:$(this).attr('data-url'),
            type:'get',
            dataType:'json',
            success:function(response){
                if(response.status=='ok'){
                    // $('#myModal').modal('show')

                    $("#modal-book .modal-content").html(response.comment_delete);

                    $("#modal-book").modal("show");
                }
            }
        })
    })
    })
  </script>
  {% endfor%}

blog/templates/blog/post_confirm_delete.html
  
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<article class="media content-section mb-0">
  <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' object.author.username%}">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
      {% if post.author == user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
  {% if request.user.is_authenticated %}
  <span class="post_likes" style="text-decoration: none;cursor: pointer;color: #007bff;"
    data-url="{% url 'post-like' post.pk %}" id="{{post.pk}}">
    <span style="margin-right: .5rem;cursor:initial;" class="text-muted " onclick=>{{post.like_set.all.count}}</span>
    <i class="fa fa-sign-language ">
    </i>
  </span>

  {% else %}

  <span style="text-decoration: none;cursor: pointer;color: #007bff;">
    <span style="margin-right: .5rem;cursor:initial;" class="text-muted ">{{post.like_set.all.count}}</span>
    <i class="fa fa-sign-language " onclick="redirectToLogin()">
    </i>
  </span>
  {% endif %}
</article>

<!-- comment sections is here  -->

<article class="media content-section comment">
  <h3 class="comment__discussion">Discussions</h3>
  <div class="container comment__body">
    {% if request.user.is_authenticated %}
    <div class="profile col-md-2 ">
      <img class="rounded-circle article-img" src={{request.user.profile.image.url}} alt="" style="margin: 0%;">
    </div>
    {% else %}
    <div class="profile col-md-2 ">
      <img class="rounded-circle article-img" src="/media/default.png/" alt="" style="margin: 0%;">
    </div>
    {% endif %}
    <div class="form-floating col-md-10 " id="commentBox">
      {% if request.user.is_authenticated %}
      <textarea class="form-control comments" placeholder="Add to the Discussions" id="content"
        style="padding: 2rem;border-radius: 10px;" value="" ></textarea>
        <small style="color: red;"></small>
      {% else %}
      <textarea class="form-control comments" placeholder="Add to the Discussions" id="content"
        style="padding: 2rem;border-radius: 10px;" value="" onclick="window.location='/login/'"></textarea>
        <small style="color: red;"></small>
        {% endif %}
    </div>

  </div>

  <button class="btn btn-outline-primary submit" type="submit" style="margin-left: 7.7rem;margin-top: 1rem;"
    data-url="{% url 'post-comment' post.pk %}">Submit</button>
  <div class="add__comments" style="width: 100%;">

  </div>

  <!-- THE MODAL WE WILL BE USING -->
  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
</article>


<script>
  function RenderAllcomments() {
    // render all comments

    $.ajax({
      url: $('.submit').attr('data-url'),
      type: 'get',

      dataType: 'json',
      success: function (response) {
        $('.add__comments').html(response.comments)
      }
    })
  }

  RenderAllcomments()


  $(function () {


    $('.submit').click(function (e) {

      e.preventDefault()
      if ($('#content').val() == '') {
        $('small').text("Field cannot be blank")
        document.getElementById("content").style.borderColor="red"
      }
      else{
        $('small').text("")
        document.getElementById("content").style.borderColor="#ced4da"
        $.ajax({
        url: $(this).attr('data-url'),
        type: 'POST',
        data: {
          'comment': $('.comments').val(),
          csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        dataType: 'json',
        success: function (response) {
          if (response) {
            $('.comments').val("")
            RenderAllcomments()
          }
        }
      })
    }
     
      
      return false
    })
  })
  function redirectToLogin() {

    window.location = '/login/'
  }
  $(function () {

    $('.post_likes').click(function () {
      var id = $(this).attr('id')
      console.log(id);
      $.ajax({
        url: $(this).attr('data-url'),
        type: 'get',
        data: { 'pk': $(this).attr('data-id') },
        dataType: 'json',
        success: function (response) {

          $('#' + id).find('span').text(response.total_likes)

        }
      })
    })

    // jquery stop child triggering parent event
    $(".post_likes span").click(function (e) {
      e.stopPropagation();
    });

  })




</script>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
      
    </div>
{% endblock content %}

blog/templates/blog/update_comment.html
      
        <!-- Modal Header -->
        
        <div class="modal-header">
          <h4 class="modal-title">Editing comment</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <textarea  id="popup_content"  class="form-control" name="popup_content">{{content.content}}</textarea>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
        <button type="button" class="btn btn-outline-primary update_comment" data-dismiss="modal" data-url="{% url 'comment-update' content.pk %}">Submit</button>
        </div>
        

    <script>
$(function(){
    $('.update_comment').click(function(e){
     console.log($('#popup_content').val());
        e.preventDefault()
        $.ajax({
            url:$(this).attr('data-url'),
            type:'post',
            data:{
                'content':$('#popup_content').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            dataType:'json',
            success:function(response){
                RenderAllcomments()
            }
        })
    })
return false
  
})
    </script>

blog/templates/blog/user_posts.html
{% extends 'blog/base.html'%}
{% block content %}
<h1 class="mb-3">Posts by {{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
{% for post in posts %}
<article class="media content-section">
  <img class="rounded-circle article-img" src={{post.author.profile.image.url}} alt="">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' post.author.username%}">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted|date:"F d,Y"}}</small>
      </div>
      <h2><a class="article-title" href="{% url 'post-detail' post.pk%}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
{% endfor %}
{% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}

{% endblock content %}